In [7]:
import pandas as pd
import numpy as np

data = pd.read_csv('fifa21_train.csv')

def read_data(data):    
    display(data)
    data.shape
    #column_names = data.columns
def clean_missing_data():
    #subset_1 = data[["Position", "Joined","Volleys","Curve","Agility","Balance","Jumping","Interceptions","Positioning","Vision","Composure","Sliding Tackle","A/W","D/W" ]]
    #data_2=data.dropna(axis=0)
    data.dropna(axis=0)
    # Reset index after drop
    data.dropna().reset_index(drop=True)
    # Drop row that has all NaN values
    data.dropna(how='all')
    #  check duplicates,frequencies or irrelevant observations
    display(data['A/W'].unique())
    display(data['A/W'].isna()==False)
    display(data['A/W'].value_counts())
    display(data['D/W'].unique())
    display(data['D/W'].isna()==False)
    display(data['D/W'].value_counts())
    #My Action: i replace all the Nan values with low since I have no idea what these terminologies stand for
    data["A/W"].replace({np.nan: "Low"}, inplace=True)
    data["D/W"].replace({np.nan: "Low"}, inplace=True)
    #cleaned subset
    #subset_3 = data_2[["Position", "Joined","Volleys","Curve","Agility","Balance","Jumping","Interceptions","Positioning","Vision","Composure","Sliding Tackle","A/W","D/W" ]]
    #display(subset_3)
    #data = data_2
    # now i will iterate Manually.. coz i dont know how to use a loop here ..
    # I am now cleaning the Volleys, Curve,Agility,Balance,Jumping
    #trying to replace NaNs
    # by the way the following also helps but i wont do it ;)
    # df.groupby(['No', 'Name'], dropna=False, as_index=False).size()

    #subset_4 = data[["Volleys","Curve","Agility","Balance","Jumping"]]
    #display(subset_4)
    # since this is a continous variable it is safe to use the following code
    #display(data['Volleys'].unique())
    #display(data['Volleys'].isna()==False)
    #display(data['Volleys'].value_counts())
    # since this is a continous variable it is safe to use the following code
    display(data['Volleys'].isnull().sum())
    #output: I have 41 occurances of this, so i approximate them to 0.0
    data["Volleys"].replace({np.nan: 0.0}, inplace=True)
    display(data['Volleys'].isnull().sum())
    
    # Clean Position
    display(data['Position'].isnull().sum())
    
    # Check again for all the coloumns with missing data
    nans_indices = data.columns[data.isna().any()].tolist()
    nans_indices


    #CLEANING SOME MORE
    
    # Clean Curve
    display(data['Curve'].unique())
    display(data['Curve'].isnull().sum())
    #output: I have 41 occurances of this, so i approximate them to 0.0
    data['Curve'].replace({np.nan: 0.0}, inplace=True)
    display(data['Curve'].isnull().sum())

    # Clean Agility
    display(data['Agility'].unique())
    display(data['Agility'].isnull().sum())
    #output: I have 41 occurances of this, so i approximate them to 0.0
    data['Agility'].replace({np.nan: 0.0}, inplace=True)
    display(data['Agility'].isnull().sum())

    # Clean Balance
    display(data['Balance'].unique())
    display(data['Balance'].isnull().sum())
    #output: I have 41 occurances of this, so i approximate them to 0.0
    data['Balance'].replace({np.nan: 0.0}, inplace=True)
    display(data['Balance'].isnull().sum())

    # Clean Jumping
    display(data['Jumping'].unique())
    display(data['Jumping'].isnull().sum())
    #output: I have 41 occurances of this, so i approximate them to 0.0
    data['Jumping'].replace({np.nan: 0.0}, inplace=True)
    display(data['Jumping'].isnull().sum())
    # Clean Position
    display(data['Position'].isnull().sum())
    data
    
    #CHeck and clean for the special symbols, other datatypes etc...
    
def preprocess():
    #print('original data and its length are as folows:')
    cols = data.columns
    cols
    #print('numeric data and its length are as folows:')
    numerical_data = data._get_numeric_data().columns
    catergorical_data = list(set(cols) - set(numerical_data))
    
       
    #rafael's solution
    df_num = data.select_dtypes(include=np.number)
    #df_cat =df.select_dtypes(include=object)
    df_num_columns = df_num.columns.tolist()
    print('NUmerical variables list')
    display(df_num_columns)
    #df_cat_columns = list(df_cat.columns)
    print('we have sorted numeric and categoric data')
    #Clara's adivice
    #column_datatypes = fifa.dtypes
    #column_datatypes
    #float64_columns = column_datatypes[column_datatypes == 'float64']
    #float64_columns
    #float64_columns.index.to_list() #this is to list all the elements that are categorical
    #categorical_columns = column_datatypes[column_datatypes != 'float64']
    #categorical_columns.index.to_list() #this is to list all the elements that are numerical
    
def clean_dataframe():
    #save the original file
    display(data)
    data.to_pickle("data_cleaned.csv")
    return data


read_data(data)
preprocess()
clean_missing_data()
clean_dataframe()

ID            Name  Age  Nationality                        Club  \
0      184383       A. Pasche   26  Switzerland           FC Lausanne-Sport   
1      188044   Alan Carvalho   30     China PR     Beijing Sinobo Guoan FC   
2      184431     S. Giovinco   33        Italy                    Al Hilal   
3      233796        J. Evans   22        Wales                Swansea City   
4      234799      Y. Demoncy   23       France  US Orléans Loiret Football   
...       ...             ...  ...          ...                         ...   
11696  232504   B. Böðvarsson   25      Iceland       Jagiellonia Białystok   
11697  214680       G. Gallon   27       France                ESTAC Troyes   
11698  221489       J. Flores   22        Chile              CD Antofagasta   
11699  146717  Anderson Silva   26       Brazil                    Barnsley   
11700  236507     T. Conechny   22    Argentina            Portland Timbers   

        BP   Position                               Team & Contract Height  \
0       CM     CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"   
1       ST   ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"   
2      CAM     CAM CF                          Al Hilal 2019 ~ 2022   5'4"   
3      CDM     CDM CM                      Swansea City 2016 ~ 2021  5'10"   
4      CDM     CDM CM        US Orléans Loiret Football 2018 ~ 2021  5'11"   
...    ...        ...                                           ...    ...   
11696   LB         LB             Jagiellonia Białystok 2018 ~ 2021   6'1"   
11697   GK         GK                      ESTAC Troyes 2019 ~ 2022   6'1"   
11698   RM  LM CAM RM                    CD Antofagasta 2019 ~ 2024   5'6"   
11699   CM        NaN                                 Barnsley 2010   6'2"   
11700  CAM  ST CAM LM                  Portland Timbers 2019 ~ 2020   5'7"   

       Weight  ...   CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0      161lbs  ...  59+1  59+1  59+1  58+1  54+1  54+1  54+1  58+1  15+1   64  
1      159lbs  ...  53+2  53+2  57+2  53+2  48+2  48+2  48+2  53+2  18+2   77  
2      134lbs  ...  56+2  56+2  59+2  53+2  41+2  41+2  41+2  53+2  12+2   80  
3      152lbs  ...  58+2  58+2  56+2  57+2  58+2  58+2  58+2  57+2  14+2   59  
4      150lbs  ...  64+2  64+2  64+2  63+2  61+2  61+2  61+2  63+2  15+2   65  
...       ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  
11696  168lbs  ...  60+2  60+2  63+2  63+2  61+2  61+2  61+2  63+2  16+2   65  
11697  174lbs  ...  26+2  26+2  25+2  24+2  26+2  26+2  26+2  24+2  69+2   70  
11698  143lbs  ...  44+2  44+2  49+2  45+2  35+2  35+2  35+2  45+2  17+2   67  
11699  179lbs  ...  68+0  68+0  66+0  64+0  60+0  60+0  60+0  64+0  25+0   68  
11700  143lbs  ...  43+2  43+2  46+2  44+2  36+2  36+2  36+2  44+2  15+2   64  

[11701 rows x 101 columns]

NUmerical variables list


['ID',
 'Age',
 'Growth',
 'Attacking',
 'Crossing',
 'Finishing',
 'Heading Accuracy',
 'Short Passing',
 'Volleys',
 'Skill',
 'Dribbling',
 'Curve',
 'FK Accuracy',
 'Long Passing',
 'Ball Control',
 'Movement',
 'Acceleration',
 'Sprint Speed',
 'Agility',
 'Reactions',
 'Balance',
 'Power',
 'Shot Power',
 'Jumping',
 'Stamina',
 'Strength',
 'Long Shots',
 'Mentality',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Defending',
 'Marking',
 'Standing Tackle',
 'Sliding Tackle',
 'Goalkeeping',
 'GK Diving',
 'GK Handling',
 'GK Kicking',
 'GK Positioning',
 'GK Reflexes',
 'Total Stats',
 'Base Stats',
 'PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY',
 'OVA']

we have sorted numeric and categoric data


array(['High', 'Medium', 'Low', nan], dtype=object)

0         True
1         True
2         True
3         True
4         True
         ...  
11696     True
11697     True
11698     True
11699    False
11700     True
Name: A/W, Length: 11701, dtype: bool

Medium    7494
High      3548
Low        600
Name: A/W, dtype: int64

array(['Medium', 'Low', 'High', nan], dtype=object)

0         True
1         True
2         True
3         True
4         True
         ...  
11696     True
11697     True
11698     True
11699    False
11700     True
Name: D/W, Length: 11701, dtype: bool

Medium    8350
High      2027
Low       1265
Name: D/W, dtype: int64

41

0

288

array([44., 78., 89., 41., 62., 69., 55., 43., 34., 32., 42., 63., 31.,
       65., 14., 85., 37., 16., 46., 53., 27., 76., 66., 50., nan, 52.,
       28., 40., 73., 51., 75., 39., 35., 70., 56., 25., 38., 36., 72.,
       12., 58., 90., 60., 30., 68., 48., 47., 29., 45., 49., 82., 61.,
       13., 57., 80., 19., 67., 64., 84., 71., 11., 83., 59., 79., 10.,
       17., 26., 21., 54., 81., 33.,  6., 18., 22., 77., 74.,  9., 87.,
       20., 15., 88., 24.,  8., 23., 91., 86., 93.,  7., 92.,  4., 94.])

41

0

array([61., 88., 93., 59., 75., 77., 67., 34., 66., 54., 85., 52., 79.,
       62., 33., 72., 28., 36., 47., 69., 56., 86., 73., 83., nan, 48.,
       78., 51., 58., 37., 57., 60., 81., 55., 65., 64., 32., 89., 92.,
       44., 68., 40., 21., 74., 45., 31., 46., 42., 63., 76., 53., 80.,
       39., 23., 84., 71., 82., 24., 90., 30., 94., 35., 49., 70., 43.,
       41., 29., 91., 38., 50., 26., 87., 25., 27., 18., 95., 22., 96.,
       15., 20., 14., 19.])

41

0

array([82., 75., 93., 55., 69., 67., 72., 34., 62., 58., 80., 54., 71.,
       56., 73., 64., 61., 53., 37., 60., 70., 77., 68., 81., nan, 50.,
       42., 38., 83., 63., 79., 35., 92., 88., 57., 90., 86., 48., 33.,
       74., 78., 49., 46., 47., 66., 44., 84., 52., 28., 76., 85., 65.,
       24., 30., 45., 94., 43., 31., 32., 39., 59., 95., 36., 29., 51.,
       87., 21., 91., 22., 40., 41., 89., 27., 26., 25., 96., 23., 17.,
       20., 97., 19.])

41

0

array([73., 81., 34., 60., 63., 67., 55., 86., 74., 72., 58., 70., 64.,
       51., 41., 85., 61., 47., 62., 56., 80., 90., 49., nan, 68., 54.,
       71., 87., 69., 52., 83., 48., 59., 40., 37., 65., 78., 42., 79.,
       66., 75., 76., 43., 57., 50., 88., 35., 31., 89., 44., 46., 53.,
       33., 82., 45., 91., 77., 84., 92., 30., 36., 38., 39., 32., 25.,
       29., 94., 93., 27., 26., 28., 95.])

41

0

288

ID            Name  Age  Nationality                        Club  \
0      184383       A. Pasche   26  Switzerland           FC Lausanne-Sport   
1      188044   Alan Carvalho   30     China PR     Beijing Sinobo Guoan FC   
2      184431     S. Giovinco   33        Italy                    Al Hilal   
3      233796        J. Evans   22        Wales                Swansea City   
4      234799      Y. Demoncy   23       France  US Orléans Loiret Football   
...       ...             ...  ...          ...                         ...   
11696  232504   B. Böðvarsson   25      Iceland       Jagiellonia Białystok   
11697  214680       G. Gallon   27       France                ESTAC Troyes   
11698  221489       J. Flores   22        Chile              CD Antofagasta   
11699  146717  Anderson Silva   26       Brazil                    Barnsley   
11700  236507     T. Conechny   22    Argentina            Portland Timbers   

        BP   Position                               Team & Contract Height  \
0       CM     CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"   
1       ST   ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"   
2      CAM     CAM CF                          Al Hilal 2019 ~ 2022   5'4"   
3      CDM     CDM CM                      Swansea City 2016 ~ 2021  5'10"   
4      CDM     CDM CM        US Orléans Loiret Football 2018 ~ 2021  5'11"   
...    ...        ...                                           ...    ...   
11696   LB         LB             Jagiellonia Białystok 2018 ~ 2021   6'1"   
11697   GK         GK                      ESTAC Troyes 2019 ~ 2022   6'1"   
11698   RM  LM CAM RM                    CD Antofagasta 2019 ~ 2024   5'6"   
11699   CM        NaN                                 Barnsley 2010   6'2"   
11700  CAM  ST CAM LM                  Portland Timbers 2019 ~ 2020   5'7"   

       Weight  ...   CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0      161lbs  ...  59+1  59+1  59+1  58+1  54+1  54+1  54+1  58+1  15+1   64  
1      159lbs  ...  53+2  53+2  57+2  53+2  48+2  48+2  48+2  53+2  18+2   77  
2      134lbs  ...  56+2  56+2  59+2  53+2  41+2  41+2  41+2  53+2  12+2   80  
3      152lbs  ...  58+2  58+2  56+2  57+2  58+2  58+2  58+2  57+2  14+2   59  
4      150lbs  ...  64+2  64+2  64+2  63+2  61+2  61+2  61+2  63+2  15+2   65  
...       ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  
11696  168lbs  ...  60+2  60+2  63+2  63+2  61+2  61+2  61+2  63+2  16+2   65  
11697  174lbs  ...  26+2  26+2  25+2  24+2  26+2  26+2  26+2  24+2  69+2   70  
11698  143lbs  ...  44+2  44+2  49+2  45+2  35+2  35+2  35+2  45+2  17+2   67  
11699  179lbs  ...  68+0  68+0  66+0  64+0  60+0  60+0  60+0  64+0  25+0   68  
11700  143lbs  ...  43+2  43+2  46+2  44+2  36+2  36+2  36+2  44+2  15+2   64  

[11701 rows x 101 columns]

ID            Name  Age  Nationality                        Club  \
0      184383       A. Pasche   26  Switzerland           FC Lausanne-Sport   
1      188044   Alan Carvalho   30     China PR     Beijing Sinobo Guoan FC   
2      184431     S. Giovinco   33        Italy                    Al Hilal   
3      233796        J. Evans   22        Wales                Swansea City   
4      234799      Y. Demoncy   23       France  US Orléans Loiret Football   
...       ...             ...  ...          ...                         ...   
11696  232504   B. Böðvarsson   25      Iceland       Jagiellonia Białystok   
11697  214680       G. Gallon   27       France                ESTAC Troyes   
11698  221489       J. Flores   22        Chile              CD Antofagasta   
11699  146717  Anderson Silva   26       Brazil                    Barnsley   
11700  236507     T. Conechny   22    Argentina            Portland Timbers   

        BP   Position                               Team & Contract Height  \
0       CM     CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"   
1       ST   ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"   
2      CAM     CAM CF                          Al Hilal 2019 ~ 2022   5'4"   
3      CDM     CDM CM                      Swansea City 2016 ~ 2021  5'10"   
4      CDM     CDM CM        US Orléans Loiret Football 2018 ~ 2021  5'11"   
...    ...        ...                                           ...    ...   
11696   LB         LB             Jagiellonia Białystok 2018 ~ 2021   6'1"   
11697   GK         GK                      ESTAC Troyes 2019 ~ 2022   6'1"   
11698   RM  LM CAM RM                    CD Antofagasta 2019 ~ 2024   5'6"   
11699   CM        NaN                                 Barnsley 2010   6'2"   
11700  CAM  ST CAM LM                  Portland Timbers 2019 ~ 2020   5'7"   

       Weight  ...   CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0      161lbs  ...  59+1  59+1  59+1  58+1  54+1  54+1  54+1  58+1  15+1   64  
1      159lbs  ...  53+2  53+2  57+2  53+2  48+2  48+2  48+2  53+2  18+2   77  
2      134lbs  ...  56+2  56+2  59+2  53+2  41+2  41+2  41+2  53+2  12+2   80  
3      152lbs  ...  58+2  58+2  56+2  57+2  58+2  58+2  58+2  57+2  14+2   59  
4      150lbs  ...  64+2  64+2  64+2  63+2  61+2  61+2  61+2  63+2  15+2   65  
...       ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  
11696  168lbs  ...  60+2  60+2  63+2  63+2  61+2  61+2  61+2  63+2  16+2   65  
11697  174lbs  ...  26+2  26+2  25+2  24+2  26+2  26+2  26+2  24+2  69+2   70  
11698  143lbs  ...  44+2  44+2  49+2  45+2  35+2  35+2  35+2  45+2  17+2   67  
11699  179lbs  ...  68+0  68+0  66+0  64+0  60+0  60+0  60+0  64+0  25+0   68  
11700  143lbs  ...  43+2  43+2  46+2  44+2  36+2  36+2  36+2  44+2  15+2   64  

[11701 rows x 101 columns]